### ISSUE TITLE
addon or addon manager?

### ISSUE THREAD

**Issue by torkus** [klingo/WoW-AddonManager#1]
hiya, I was wondering if you had intended this project to be an addon within WoW itself, or a standalone application that inspected the addon directories?

I maintain [a list of addon managers](https://ogri-la.github.io/wow-addon-managers/) and I'm always on the look out for worthwhile features to integrate into [my own addon manager](https://github.com/ogri-la/wowman). Being able to inspect (perhaps even modify!) which addons are enabled per-character is something I've never considered.

**Comment by klingo** [comment]
Hi, this is supposed to become a standalone application that inspects the addon directories and provides an easy overview to enable/disable addons for all characters across all servers/accounts.

I have many bank chars and whenever I have a new addon or so I need to enable/disable that for all my characters. With this app I want to simplify that where it should show a list of addons (vertically) and a list of characters (horizontally) - the intersections are checkboxes to turn them on or off.
